### ISSUE TITLE
TypeError: Can't convert object to 'str' for 'filename'

### ISSUE THREAD

**Issue by Gargantuanman** [NON906/chara-searcher#3]
Hello Im having this issue if I use a video mp4 or a image folder after processing  this conver error appears.

100%|████████████████████████████████████████████████████████████████████████████████| 316/316 [01:37<00:00,  3.26it/s]
* (step 2/3) Processing tagging.
  0%|                                                                                          | 0/323 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\stable-diffusion-webui\extensions\chara-searcher\standalone_ui.py", line 65, in upload_dir_files
    tagging_main(src_images_dir)
  File "C:\stable-diffusion-webui\extensions\chara-searcher\tagging.py", line 152, in tagging_main
    tags = image_interrogate(image_path, not args.rawtag, parse_exclude_tags())
  File "C:\stable-diffusion-webui\extensions\chara-searcher\tagging.py", line 105, in image_interrogate
    image = cv2.imread(image_path, -1)
TypeError: Can't convert object to 'str' for 'filename'

**Comment by NON906** [comment]
I fixed it and committed it, so please check it out.
c903ef6b936c1fdb88fbca6e8a43a5cff5618313

**Comment by Gargantuanman** [comment]
Thank you so much it works now :D
